### ISSUE TITLE
Unknown public property "density" of element <lightning-record-edit-form>

### ISSUE THREAD

**Issue by progknife** [salesforce/sfdx-lwc-jest#80]
Test is failing because a child component with lightning-record-edit-form attribute "density" is set.

```
    Unknown public property "density" of element <lightning-record-edit-form>. This is likely a typo on the corresponding attribute "density".

      25 |       is: UserSettings,
      26 |     });
    > 27 |     document.body.appendChild(element);
         |     ^
      28 |     const handlerClick = jest.fn();
      29 |     element.addEventListener('click', handlerClick);
      30 | 

      at Object.fail (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:190:15)
      at assert (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:1795:17)
      at Object.update (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:1810:24)
      at modProps (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:5590:5)
      at Object.create$$1 [as create] (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:5768:9)
      at ch (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:4870:13)
      at addVnodes (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:4980:9)
      at fn (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:7864:17)
      at job (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:8248:9)
      at runWithBoundaryProtection (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:7857:13)
      at patchShadowRoot (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:7842:9)
      at rehydrate (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:7749:5)
      at appendVM (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:5529:5)
      at Object.insertCustomElmHook [as insert] (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:5785:9)
      at ch (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:5603:13)
      at Object.createChildrenHook [as insert] (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:5748:9)
      at ch (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:4871:13)
      at addVnodes (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:4980:9)
      at fn (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:7864:17)
      at job (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:8248:9)
      at runWithBoundaryProtection (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:7857:13)
      at patchShadowRoot (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:7842:9)
      at rehydrate (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:7749:5)
      at appendVM (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:5529:5)
      at Object.insertCustomElmHook [as insert] (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:5785:9)
      at ch (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:5603:13)
      at Object.createChildrenHook [as insert] (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:5748:9)
      at ch (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:4871:13)
      at addVnodes (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:4980:9)
      at fn (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:7864:17)
      at job (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:8248:9)
      at runWithBoundaryProtection (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:7857:13)
      at patchShadowRoot (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:7842:9)
      at rehydrate (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:7749:5)
      at appendVM (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:5529:5)
      at Object.insertCustomElmHook [as insert] (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:5785:9)
      at ch (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:5603:13)
      at Object.createChildrenHook [as insert] (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:5748:9)
      at ch (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:4871:13)
      at addVnodes (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:4980:9)
      at fn (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:7864:17)
      at job (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:8248:9)
      at runWithBoundaryProtection (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:7857:13)
      at patchShadowRoot (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:7842:9)
      at rehydrate (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:7749:5)
      at appendVM (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:5529:5)
      at Object.insertCustomElmHook [as insert] (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:5785:9)
      at ch (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:4871:13)
      at addVnodes (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:4980:9)
      at fn (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:7864:17)
      at job (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:8248:9)
      at runWithBoundaryProtection (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:7857:13)
      at patchShadowRoot (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:7842:9)
      at rehydrate (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:7741:5)
      at appendRootVM (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:8371:9)
      at fn (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:8291:9)
      at HTMLBodyElement.callNodeSlot [as appendChild] (node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:8300:16)
      at Object.document (sfdx-source/force-app/main/default/lwc/userSettings/__tests__/userSettings.test.js:27:5)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 2 total
Snapshots:   0 total
Time:        6.392s
Ran all test suites matching /userSettings/i.
```
My child component is using the the record edit form:
```
<lightning-record-edit-form density="compact></lightning-record-edit-form>
```
density attribute is documented [here](https://developer.salesforce.com/docs/component-library/bundle/lightning-record-edit-form/specification).

**Comment by trevor-bliss** [comment]
Thanks for bringing this to our attention! Fix will be in shortly.
