### ISSUE TITLE
Error running lwc-jest 

### ISSUE THREAD

**Issue by donaldrivard** [salesforce/sfdx-lwc-jest#84]
npm run test:unit

TypeError: this.setDynamic is not a function

      at PluginPass.pre (node_modules/babel-plugin-transform-runtime/lib/index.js:31:12)
      at transformFile (node_modules/@babel/core/lib/transformation/index.js:78:27)
      at runSync (node_modules/@babel/core/lib/transformation/index.js:45:3)
      at transformSync (node_modules/@babel/core/lib/transform.js:43:38)
      at Object.transform (node_modules/@babel/core/lib/transform.js:22:38)

**Comment by trevor-bliss** [comment]
Hi @donaldrivard. Could you please share a simple repro case (test case, component under test html + js) and any custom Jest config overrides you have set?

**Comment by donaldrivard** [comment]
Hi Trevor,
This appears to be a test file directory issue. I am reading the doc a bit more and just realized that this is maybe it. My directory structure for LWC is a different than default:

force-app/main/common/lwc/componentA
force-app/main/common/lwc/componentB

force-app/main/common/lwc/componentA/__tests__
force-app/main/common/lwc/componentB__tests__

Do you have an example on how these tests would run?

Thanks!

**Comment by donaldrivard** [comment]
Hi Trevor
This appears to be operator error. I have some other test classes in the tree that are being picked up. I am going through this now. If I believe there really is an issue I will reopen.

Thanks for the quick response
